# -*- coding: utf-8 -*-
"""mental treatment score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11WtJnPeJVekjPJWyFy2QQNQBxn5732ZD
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import warnings
warnings.filterwarnings('ignore')
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)
print("Imports done.")

print("numpy",np.__version__)
print("pandas",pd.__version__)
print("sklearn",sklearn.__version__)
import flask
print("flask",flask.__version__)

data = pd.read_csv('/content/drive/MyDrive/ML learning/Mental Health Survey Dataset.csv')

print(data)

print(data.info())

data = data.replace(' ?', np.nan)
data = data.replace('?', np.nan)

print(data.isna())

print(data.isnull().sum())

print("Duplicate rows:",data.duplicated().sum())

print(data.describe())

print(data.describe(include=[object]))

print("Unique values in each column:")
for col in data.columns:
    print(col, ":", data[col].nunique())

for col in data.columns:
    print("Value counts for ")
    print(data[col].value_counts())
    print("--------------------------------------------------")

num_cols = data.select_dtypes(include="number").columns
for col in num_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = ((data[col] < lower) | (data[col] > upper)).sum()
    print(col ,":", outliers ,"outliers")

drop_cols = []
for c in ['Timestamp', 'comments', 'state']:
    if c in data.columns:
        drop_cols.append(c)

print("Dropping:", drop_cols)
data = data.drop(columns=drop_cols, errors='ignore')
print("New shape:", data.shape)

data['Age'] = pd.to_numeric(data['Age'], errors='coerce')
data.loc[(data['Age'] < 16) | (data['Age'] > 100), 'Age'] = np.nan

plt.figure(figsize=(8,4))
sns.histplot(data['Age'].dropna(), bins=30)
plt.title("Age distribution")
plt.show()

num_cols = data.select_dtypes(include="number").columns
for col in num_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = ((data[col] < lower) | (data[col] > upper)).sum()
    print(col ,":", outliers ,"outliers")

data['Gender'] = data['Gender'].astype(str).str.lower().str.strip()

data['Gender'] = data['Gender'].apply(
    lambda x: 'female' if x in ['female','f','woman','cis female','female (cis)','female (trans)','femake','femail','female ']
    else 'male' if x in ['male','m','man','cis male','male (cis)','mail','mal','male ']
    else 'other'
)

print("Gender value counts:")
print(data['Gender'].value_counts())

data['work_interfere'] = data['work_interfere'].fillna(data['work_interfere'].mode()[0])
data['self_employed'] = data['self_employed'].fillna(data['self_employed'].mode()[0])

data['Age'] = data['Age'].fillna(int(data['Age'].median()))

print(data.isnull().sum())

"""Visualisation

"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6,4))
sns.countplot(x='treatment', data=data, palette='Set2')
plt.title('Distribution of Treatment')
plt.xlabel('Treatment')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x='work_interfere', hue='treatment', data=data, palette='Set1')
plt.title('Work Interference vs Treatment')
plt.xlabel('Work Interference')
plt.ylabel('Count')
plt.legend(title='Treatment')
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(data=data, x='Age', hue='treatment', multiple='stack', bins=20, palette='Set1')
plt.title('Age Distribution by Treatment')
plt.xlabel('Age')
plt.ylabel('Count')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6,4))
sns.countplot(x='Gender', data=data, palette='Set2')
plt.title('Gender Distribution')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""Encoding

"""

if 'work_interfere' in data.columns:
    data['work_interfere'] = data['work_interfere'].map({
        'Never': 0, 'Rarely': 1, 'Sometimes': 2, 'Often': 3
    }).fillna(0).astype(int)

if 'leave' in data.columns:
    data['leave'] = data['leave'].map({
        "Don't know": 0, 'Very difficult': 1, 'Somewhat difficult': 2,'Somewhat easy': 3, 'Very easy': 4
    }).fillna(0).astype(int)

if 'country' in data.columns:
    data['country'] = data['country'].apply(
        lambda x: x if data['country'].value_counts()[x] >= 20 else 'Other'
    )

print("Simple ordinal & country encoding done")

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

cat_cols = data.select_dtypes(include=['object']).columns.tolist()
print("Categorical columns:", cat_cols)

le = LabelEncoder()

data_encoded = data.copy()

for col in cat_cols:
    if data[col].nunique() <= 2:
        data_encoded[col] = le.fit_transform(data[col].astype(str))
    else:
        temp = pd.get_dummies(data[col], prefix=col)
        data_encoded = pd.concat([data_encoded, temp], axis=1)
        data_encoded.drop(col, axis=1, inplace=True)

print("Encoding done successfully")

joblib.dump(le, 'label_encoder.pkl')
print("Label Encoder saved successfully.")

data_encoded.head()

print(data_encoded.info())

"""Correlations and Heatmap

"""

corr_matrix = data_encoded.corr()
print(corr_matrix)

corr_data = data_encoded.select_dtypes(include=['int64', 'float64'])
corr_matrix = corr_data.corr()
print(corr_matrix)

target_corr = corr_matrix['treatment'].sort_values(ascending=False)
print("Correlation of each feature with treatment:\n")
print(target_corr)

plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix,annot=True, cmap='coolwarm', center=0)
plt.title("Overall Correlation Heatmap (All Numeric Features)")
plt.show()

top_features = target_corr.abs().sort_values(ascending=False).head(15).index
plt.figure(figsize=(10, 6))
sns.heatmap(corr_matrix.loc[top_features, top_features], annot=True, cmap='coolwarm', center=0)
plt.title("Top 15 Features Most Correlated with Treatment")
plt.show()

target_corr = corr_matrix['treatment'].sort_values(ascending=False)
abs_corr = target_corr.abs().sort_values(ascending=False)
print("Top 15 features most strongly correlated (positive or negative) with treatment:\n")
print(abs_corr.head(15))

plt.figure(figsize=(10, 6))
abs_corr.head(15).plot(kind='bar')
plt.title('Top 15 Features Most Strongly Correlated with Treatment')
plt.ylabel('Absolute Correlation')
plt.xlabel('Features')
plt.xticks(rotation=45)
plt.show()

"""Model Training

"""

X = data_encoded.drop('treatment', axis=1)
y = data_encoded['treatment']

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training features shape:", X_train.shape)
print("Testing features shape:", X_test.shape)
print("Training target shape:", y_train.shape)
print("Testing target shape:", y_test.shape)

# --- Class balance check (paste right after X and y defined) ---
import pandas as pd
print("Target distribution:")
print(pd.Series(y).value_counts())
counts = pd.Series(y).value_counts().to_dict()
print("Counts:", counts)

joblib.dump(X.columns.tolist(), 'columns.pkl')
print("Column names saved successfully.")

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Data scaled successfully")

joblib.dump(scaler, 'scaler.pkl')
print("Scaler saved successfully.")

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

import seaborn as sns
import matplotlib.pyplot as plt
cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

accuracy_scores = []

for k in range(1, 21):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train)
    y_pred = knn.predict(X_test_scaled)
    score = accuracy_score(y_test, y_pred)
    accuracy_scores.append(score)

plt.figure(figsize=(8,5))
plt.plot(range(1, 21), accuracy_scores, marker='o', color='blue')
plt.title("Accuracy vs K Value (KNN)")
plt.xlabel("Number of Neighbors (K)")
plt.ylabel("Accuracy")
plt.grid(True)
plt.xticks(range(1, 21))
plt.show()

best_k = accuracy_scores.index(max(accuracy_scores)) + 1
print("Best K value:", best_k)
print("Highest Accuracy:", max(accuracy_scores))

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

knn = KNeighborsClassifier(n_neighbors=16)
knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

print("KNN Classifier Evaluation:")
print("Accuracy:", accuracy_score(y_test, y_pred_knn))
print("\nClassification Report:\n", classification_report(y_test, y_pred_knn))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))

"""Decision Tree"""

from sklearn.tree import DecisionTreeClassifier

accuracy_scores = []

for depth in range(1, 21):
    dt = DecisionTreeClassifier(max_depth=depth, random_state=42)
    dt.fit(X_train, y_train)
    y_pred = dt.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    accuracy_scores.append(acc)

plt.figure(figsize=(8,5))
plt.plot(range(1, 21), accuracy_scores, marker='o', linestyle='-', color='green')
plt.title("Accuracy vs max_depth (Decision Tree)")
plt.xlabel("max_depth")
plt.ylabel("Accuracy")
plt.grid(True)
plt.xticks(range(1, 21))
plt.show()

best_depth = accuracy_scores.index(max(accuracy_scores)) + 1
print("Best max_depth:", best_depth)
print("Highest Accuracy:", max(accuracy_scores))

final_tree = DecisionTreeClassifier(max_depth=best_depth, random_state=42)
final_tree.fit(X_train, y_train)
y_pred_tree = final_tree.predict(X_test)

print("Final Decision Tree Results:")
print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Classification Report:\n", classification_report(y_test, y_pred_tree))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_tree))

"""Random Forest"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

accuracy_scores = []

for n in range(10, 110, 10):
    rf = RandomForestClassifier(n_estimators=n, random_state=42)
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    accuracy_scores.append(acc)

plt.figure(figsize=(8,5))
plt.plot(range(10, 110, 10), accuracy_scores, marker='o', linestyle='-', color='red')
plt.title("Accuracy vs Number of Trees (Random Forest)")
plt.xlabel("Number of Trees (n_estimators)")
plt.ylabel("Accuracy")
plt.grid(True)
plt.xticks(range(10, 110, 10))
plt.show()

best_n = range(10, 110, 10)[accuracy_scores.index(max(accuracy_scores))]
print("Best n_estimators:", best_n)
print("Highest Accuracy:", max(accuracy_scores))

final_rf = RandomForestClassifier(n_estimators=best_n, random_state=42)
final_rf.fit(X_train, y_train)
y_pred_rf = final_rf.predict(X_test)

print("Final Random Forest Model Results:")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

import numpy as np
import matplotlib.pyplot as plt

models = ['Logistic Regression', 'KNN', 'Random Forest']
accuracy = [0.698, 0.671, 0.75]
precision = [0.70, 0.68, 0.75]
recall = [0.70, 0.67, 0.75]
f1 = [0.70, 0.66, 0.75]

x = np.arange(len(models))
width = 0.2

plt.figure(figsize=(10,6))
plt.bar(x - width*1.5, accuracy, width, label='Accuracy', color='blue')
plt.bar(x - width/2, precision, width, label='Precision', color='green')
plt.bar(x + width/2, recall, width, label='Recall', color='orange')
plt.bar(x + width*1.5, f1, width, label='F1-Score', color='red')

plt.xlabel('Models', fontsize=12)
plt.ylabel('Score', fontsize=12)
plt.title('Comparison of Models for Treatment Prediction', fontsize=14)
plt.xticks(x, models)
plt.ylim(0, 1)
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

import pandas as pd

model_comparison = pd.DataFrame({
    'Model': ['Logistic Regression', 'K-Nearest Neighbors', 'Random Forest'],
    'Accuracy': [0.698, 0.671, 0.75],
    'Precision': [0.70, 0.68, 0.75],
    'Recall': [0.70, 0.67, 0.75],
    'F1-Score': [0.70, 0.66, 0.75]
})

best_model = model_comparison.loc[model_comparison['Accuracy'].idxmax(), 'Model']
print(" Best Model for this dataset:", best_model)

model_comparison

joblib.dump(final_rf, 'mental_health_model.pkl')
print("Final Random Forest model saved successfully.")

import pandas as pd
import matplotlib.pyplot as plt

feature_importances = pd.Series(final_rf.feature_importances_, index=X.columns).sort_values(ascending=False)
plt.figure(figsize=(10,6))
feature_importances.head(15).plot(kind='bar', color='teal')
plt.title("Top 15 Important Features (Random Forest)")
plt.ylabel("Feature Importance Score")
plt.show()

print("Original numerical columns:", num_cols.tolist())
print("Original categorical columns:", cat_cols)

print("Dropped columns:", drop_cols)

from sklearn.model_selection import cross_val_score

scores = cross_val_score(final_rf, X, y, cv=5, scoring='accuracy')
print("Cross-Validation Accuracy:", scores)
print("Mean CV Accuracy:", scores.mean())

y_proba = final_rf.predict_proba(X_test_scaled)[:, 1]
test_results = pd.DataFrame({'True Label': y_test, 'Predicted Label': y_pred_rf})
test_results['Probability'] = y_proba

print(test_results.head(10))

model = final_rf
sample = X_test.sample(1, random_state=42)
sample_scaled = scaler.transform(sample)

pred = model.predict(sample_scaled)[0]
prob = model.predict_proba(sample_scaled)[0][1]
score = round(prob * 100, 2)

print("Sample Data Index:", sample.index[0])
print("Predicted Class:", pred)
print("Probability of Needing Treatment:", prob)
print("Mental Health Treatment Likelihood Score:", score, "/ 100")

if score < 40:
    message = "No, treatment may not be needed (Low Risk)"
elif 40 <= score <= 70:
    message = "You might want to consult a professional (Moderate Risk)"
else:
    message = "Yes, treatment is likely recommended (High Risk)"

print("Prediction Message:", message)

import joblib
joblib.dump(final_rf, "treatment_prediction_model.pkl")
joblib.dump(scaler, "scaler.pkl")

# Test loading of saved files
loaded_scaler = joblib.load('scaler.pkl')
loaded_columns = joblib.load('columns.pkl')
loaded_encoder = joblib.load('label_encoder.pkl')

print("All saved files loaded successfully!")

# Optional quick test prediction (using a few test samples)
sample = X_test.iloc[:5]
sample_scaled = loaded_scaler.transform(sample)
print("Predicted:", loaded_model.predict(sample_scaled))

import pickle
from google.colab import files