# -*- coding: utf-8 -*-
"""student_stress_quiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mDB0qNaJivWvo-dnGldGjLe0SsEFhtvH
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

zip_path = "/content/drive/MyDrive/ML learning/archive (11).zip"

import zipfile
import os

extract_folder = "/content/student_dataset"
os.makedirs(extract_folder, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

extract_folder

import os
os.listdir(extract_folder)

import pandas as pd

df1 = pd.read_csv(extract_folder + "/StressLevelDataset.csv")
df2 = pd.read_csv(extract_folder + "/Stress_Dataset.csv")

print("DF1 Shape:", df1.shape)
print("DF2 Shape:", df2.shape)

print(df1)
print(df2)

print(df1.columns)
print(df2.columns)

df = df1.copy()

print(df)

print(df.info())

df = df.replace(' ?', np.nan)
df = df.replace('?', np.nan)

print(df.isna())

print(df.isnull().sum())

print("Duplicate rows:",df.duplicated().sum())

print(df.describe())

print("Unique values in each column:")
for col in df.columns:
    print(col, ":", df[col].nunique())

for col in df.columns:
    print("Value counts for ")
    print(df[col].value_counts())
    print("--------------------------------------------------")

correlation_df= df.corr()

# Create a heatmap
plt.figure(figsize=(14, 10))
sns.heatmap(data=correlation_df, annot=True, cmap='coolwarm')
plt.title("What tends to a higher stress level?", fontweight='bold')
plt.show()

average_anxiety = df['anxiety_level'].mean().round(2)
print('Average anxiety of students in this dataset is ', average_anxiety)

# Visualizing anxiety levels in students
plt.figure(figsize=(8,6))
ax = sns.histplot(data=df, x='anxiety_level', bins=20, color='lightcoral')
plt.title('Anxiety Levels in students')
plt.xlabel('Anxity Level')
plt.ylabel('Number of Students')
plt.show()

print("\nTarget distribution:\n", df['stress_level'].value_counts().sort_index())
plt.figure(figsize=(5,3))
sns.countplot(x='stress_level', data=df)
plt.title('Stress Level Distribution (0=Low, 1=Moderate, 2=High)')
plt.show()

from sklearn.model_selection import train_test_split
X = df.drop('stress_level', axis=1)
y = df['stress_level']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

print("Class counts:\n", y.value_counts().sort_index())

joblib.dump(X_train.columns.tolist(), 'student_columns.pkl')
print("Saved feature column names to student_columns.pkl")

print("Training features shape:", X_train.shape)
print("Testing features shape:", X_test.shape)
print("Training target shape:", y_train.shape)
print("Testing target shape:", y_test.shape)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
joblib.dump(scaler, 'student_scaler.pkl')
print("Scaler saved successfully student_scaler.pkl")

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

import seaborn as sns
import matplotlib.pyplot as plt
cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

accuracy_scores = []

for k in range(1, 21):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train)
    y_pred = knn.predict(X_test_scaled)
    score = accuracy_score(y_test, y_pred)
    accuracy_scores.append(score)

plt.figure(figsize=(8,5))
plt.plot(range(1, 21), accuracy_scores, marker='o', color='blue')
plt.title("Accuracy vs K Value (KNN)")
plt.xlabel("Number of Neighbors (K)")
plt.ylabel("Accuracy")
plt.grid(True)
plt.xticks(range(1, 21))
plt.show()

best_k = accuracy_scores.index(max(accuracy_scores)) + 1
print("Best K value:", best_k)
print("Highest Accuracy:", max(accuracy_scores))

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

print("KNN Classifier Evaluation:")
print("Accuracy:", accuracy_score(y_test, y_pred_knn))
print("\nClassification Report:\n", classification_report(y_test, y_pred_knn))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))

from sklearn.tree import DecisionTreeClassifier

accuracy_scores = []

for depth in range(1, 21):
    dt = DecisionTreeClassifier(max_depth=depth, random_state=42)
    dt.fit(X_train_scaled, y_train)  # Use scaled data
    y_pred = dt.predict(X_test_scaled)  # Use scaled data
    acc = accuracy_score(y_test, y_pred)
    accuracy_scores.append(acc)

# ... rest of plotting code stays same ...

plt.figure(figsize=(8,5))
plt.plot(range(1, 21), accuracy_scores, marker='o', linestyle='-', color='green')
plt.title("Accuracy vs max_depth (Decision Tree)")
plt.xlabel("max_depth")
plt.ylabel("Accuracy")
plt.grid(True)
plt.xticks(range(1, 21))
plt.show()

best_depth = accuracy_scores.index(max(accuracy_scores)) + 1
print("Best max_depth:", best_depth)
print("Highest Accuracy:", max(accuracy_scores))

final_tree = DecisionTreeClassifier(max_depth=best_depth, random_state=42)
final_tree.fit(X_train_scaled, y_train)
y_pred_tree = final_tree.predict(X_test_scaled)

print("Final Decision Tree Results:")
print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Classification Report:\n", classification_report(y_test, y_pred_tree))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_tree))

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

accuracy_scores = []

for n in range(10, 110, 10):
    rf = RandomForestClassifier(n_estimators=n, random_state=42)
    rf.fit(X_train_scaled, y_train)  # Use scaled data
    y_pred = rf.predict(X_test_scaled)  # Use scaled data
    acc = accuracy_score(y_test, y_pred)
    accuracy_scores.append(acc)

# ... plotting code stays same ...

plt.figure(figsize=(8,5))
plt.plot(range(10, 110, 10), accuracy_scores, marker='o', linestyle='-', color='red')
plt.title("Accuracy vs Number of Trees (Random Forest)")
plt.xlabel("Number of Trees (n_estimators)")
plt.ylabel("Accuracy")
plt.grid(True)
plt.xticks(range(10, 110, 10))
plt.show()

best_n = range(10, 110, 10)[accuracy_scores.index(max(accuracy_scores))]
print("Best n_estimators:", best_n)
print("Highest Accuracy:", max(accuracy_scores))

final_rf = RandomForestClassifier(n_estimators=best_n, random_state=42)
final_rf.fit(X_train_scaled, y_train)  # Use scaled data
y_pred_rf = final_rf.predict(X_test_scaled)  # Use scaled data

print("Final Random Forest Model Results:")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

import numpy as np
import matplotlib.pyplot as plt

models   = ['LogReg', 'KNN', 'Decision Tree', 'Random Forest']

# Updated metrics (macro averages + accuracy)
accuracy = [0.8818, 0.8500, 0.8727, 0.8909]
precision= [0.88,   0.85,   0.89,   0.89]
recall   = [0.88,   0.85,   0.87,   0.89]
f1       = [0.88,   0.85,   0.88,   0.89]

x = np.arange(len(models))
width = 0.18

plt.figure(figsize=(12,6))
plt.bar(x - width*1.5, accuracy,  width, label='Accuracy',  color='blue')
plt.bar(x - width/2,  precision, width, label='Precision', color='green')
plt.bar(x + width/2,  recall,    width, label='Recall',    color='orange')
plt.bar(x + width*1.5,f1,        width, label='F1-Score',  color='red')

plt.xlabel('Models', fontsize=12)
plt.ylabel('Score', fontsize=12)
plt.title('Model Comparison — Student Stress Prediction', fontsize=14)
plt.xticks(x, models)
plt.ylim(0, 1)
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

proba = final_rf.predict_proba(X_test_scaled)
high_class_index = list(final_rf.classes_).index(2)

df_results = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred_rf,
    "P(HighStress)": proba[:, high_class_index]
})

df_results["Stress_Score"] = (df_results["P(HighStress)"] * 100).round(2)

print(df_results.head(10))

def interpret(score):
    if score < 40:
        return "Low Stress - You're doing great! Keep up healthy habits. 😊"
    elif 40 <= score <= 70:
        return "Moderate Stress - Consider stress management techniques or talking to someone. 🤔"
    else:
        return "High Stress - Please reach out to a counselor or healthcare professional. ⚠️"

df_results["Stress_Level_Interpretation"] = df_results["Stress_Score"].apply(interpret)
df_results["Band"] = df_results["Stress_Score"].apply(
    lambda s: "Low" if s < 40 else "Moderate" if s <= 70 else "High"
)

print(df_results.head(10))

# Save all artifacts needed for deployment
joblib.dump(final_rf, 'student_stress_rf_model.pkl')
joblib.dump(X_train.columns.tolist(), 'student_columns.pkl')
joblib.dump(scaler, 'student_scaler.pkl')
joblib.dump({'low':(0,40),'moderate':(40,70),'high':(70,100)}, 'student_stress_meta.pkl')
print("Saved: model, columns, scaler, meta")

def predict_scores(df_like):
    """
    Predicts stress scores for multiple students at once.
    Input: DataFrame with same columns as training data
    Output: DataFrame with predictions
    """
    cols = joblib.load('student_columns.pkl')
    model = joblib.load('student_stress_rf_model.pkl')
    scaler = joblib.load('student_scaler.pkl')

    X_scaled = scaler.transform(df_like[cols])

    hi = list(model.classes_).index(2)
    P = model.predict_proba(X_scaled)[:, hi]
    S = (P * 100).round(2)
    C = model.predict(X_scaled)
    B = ["Low" if s < 40 else "Moderate" if s <= 70 else "High" for s in S]
    M = [interpret(s) for s in S]

    return pd.DataFrame({
        "predicted_class": C,
        "p_high": P,
        "stress_score": S,
        "band": B,
        "message": M
    }, index=df_like.index)

print("\n🧪 Testing prediction function:")
test_results = predict_scores(X_test.head(5))
print(test_results)

stress_level_counts = df['stress_level'].value_counts()

plt.figure(figsize=(6, 6))
plt.pie(stress_level_counts, labels=stress_level_counts.index, autopct='%1.1f%%', colors=['skyblue', 'lightgreen', 'lightcoral'])
plt.title('Distribution of Stress Levels')
plt.show()

key_features = ['anxiety_level', 'depression', 'self_esteem', 'sleep_quality']

for feature in key_features:
    plt.figure(figsize=(8, 6))
    sns.histplot(data=df, x=feature, bins=20, color='skyblue')
    plt.title(f'{feature.replace("_", " ").title()} Distribution')
    plt.xlabel(f'{feature.replace("_", " ").title()} Level')
    plt.ylabel('Number of Students')
    plt.show()

importances = final_rf.feature_importances_

feature_importances = pd.Series(importances, index=X_train.columns)

feature_importances = feature_importances.sort_values(ascending=False)

top_n = 15
top_features = feature_importances.head(top_n)

plt.figure(figsize=(10, 6))
sns.barplot(x=top_features.values, y=top_features.index, hue=top_features.index, palette='viridis', legend=False)

plt.title(f'Top {top_n} Most Important Features for Stress Level Prediction (Random Forest)')
plt.xlabel('Feature Importance Score')
plt.ylabel('Features')

plt.tight_layout()
plt.show()

