const questionnew = [
  {
    field: "anxiety_level",
    question: "In the past 2 weeks, how often did you feel anxious or on edge?",
    min: 0,
    max: 30,
    scale: { "0": "Not at all", "30": "All the time" },
  },
  {
    field: "self_esteem",
    question: "Overall, how confident do you feel about yourself right now?",
    min: 0,
    max: 30,
    scale: { "0": "Not confident", "30": "Extremely confident" },
  },
  {
    field: "mental_health_history",
    question: "Have you ever been diagnosed with a mental health condition?",
    options: { "0": "No", "1": "Yes" },
  },
  {
    field: "depression",
    question: "In the past 2 weeks, how often did you feel sad, down, or hopeless?",
    min: 0,
    max: 30,
    scale: { "0": "Not at all", "30": "All the time" },
  },
  {
    field: "headache",
    question: "How often do you get headaches?",
    min: 0,
    max: 5,
    scale: { "0": "Never", "5": "Very often" },
  },
  {
    field: "blood_pressure",
    question: "How would you describe your usual blood pressure?",
    options: { "1": "Low", "2": "Normal", "3": "High" },
  },
  {
    field: "sleep_quality",
    question: "How would you rate your sleep quality recently?",
    min: 0,
    max: 5,
    scale: { "0": "Very poor", "5": "Excellent" },
  },
  {
    field: "breathing_problem",
    question: "Do you experience breathing difficulties (e.g., shortness of breath)?",
    min: 0,
    max: 5,
    scale: { "0": "Never", "5": "Very often" },
  },
  {
    field: "noise_level",
    question: "How noisy is your usual study/living environment?",
    min: 0,
    max: 5,
    scale: { "0": "Very quiet", "5": "Very noisy" },
  },
  {
    field: "living_conditions",
    question: "How would you rate your living conditions?",
    min: 1,
    max: 5,
    scale: { "1": "Very poor", "5": "Excellent" },
  },
  {
    field: "safety",
    question: "Do you feel physically and emotionally safe where you live/study?",
    min: 1,
    max: 5,
    scale: { "1": "Not safe", "5": "Very safe" },
  },
  {
    field: "basic_needs",
    question: "Are your basic needs (food, water, shelter) consistently met?",
    min: 1,
    max: 5,
    scale: { "1": "Rarely", "5": "Always" },
  },
  {
    field: "academic_performance",
    question: "How would you rate your academic performance at the moment?",
    min: 1,
    max: 5,
    scale: { "1": "Very poor", "5": "Excellent" },
  },
  {
    field: "study_load",
    question: "How heavy is your current study workload?",
    min: 1,
    max: 5,
    scale: { "1": "Very light", "5": "Extremely heavy" },
  },
  {
    field: "teacher_student_relationship",
    question: "How is your relationship with your teachers/faculty?",
    min: 1,
    max: 5,
    scale: { "1": "Very poor", "5": "Excellent" },
  },
  {
    field: "future_career_concerns",
    question: "How worried are you about your future career?",
    min: 1,
    max: 5,
    scale: { "1": "Not worried", "5": "Extremely worried" },
  },
  {
    field: "social_support",
    question: "How much social support do you feel you have (friends/family)?",
    min: 0,
    max: 3,
    scale: { "0": "None", "3": "A lot" },
  },
  {
    field: "peer_pressure",
    question: "How often do you feel pressured by peers to do things?",
    min: 0,
    max: 5,
    scale: { "0": "Never", "5": "Very often" },
  },
  {
    field: "extracurricular_activities",
    question: "How involved are you in extracurricular activities?",
    min: 0,
    max: 5,
    scale: { "0": "Not involved", "5": "Highly involved" },
  },
  {
    field: "bullying",
    question: "Have you experienced bullying recently?",
    min: 0,
    max: 5,
    scale: { "0": "Never", "5": "Very often" },
  },
];

module.exports = { questionnew };
